import { Octokit } from '@octokit/rest'

export function createOctokit(token: string): Octokit {
  return new Octokit({ auth: token })
}

export function parseRepoUrl(url: string): {
  owner: string
  repo: string
} | null {
  const patterns = [
    /github\.com\/([^/]+)\/([^/\s#?]+)/,
    /^([^/]+)\/([^/\s]+)$/,
  ]

  for (const pattern of patterns) {
    const match = url.match(pattern)
    if (match) {
      return {
        owner: match[1],
        repo: match[2].replace(/\.git$/, ''),
      }
    }
  }

  return null
}

export async function getDefaultBranch(
  octokit: Octokit,
  owner: string,
  repo: string
): Promise<string> {
  const { data } = await octokit.repos.get({ owner, repo })
  return data.default_branch
}

export async function createPR(
  octokit: Octokit,
  owner: string,
  repo: string,
  jobId: string,
  files: Map<string, string>
): Promise<string> {
  const defaultBranch = await getDefaultBranch(octokit, owner, repo)

  const { data: refData } = await octokit.git.getRef({
    owner,
    repo,
    ref: `heads/${defaultBranch}`,
  })
  const baseSha = refData.object.sha

  const branchName = `lazarus-resurrection-${jobId.slice(0, 8)}`
  await octokit.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha: baseSha,
  })

  const blobs = await Promise.all(
    Array.from(files.entries()).map(async ([path, content]) => {
      const { data } = await octokit.git.createBlob({
        owner,
        repo,
        content: Buffer.from(content).toString('base64'),
        encoding: 'base64',
      })
      return { path, sha: data.sha, mode: '100644' as const, type: 'blob' as const }
    })
  )

  const { data: tree } = await octokit.git.createTree({
    owner,
    repo,
    base_tree: baseSha,
    tree: blobs,
  })

  const { data: commit } = await octokit.git.createCommit({
    owner,
    repo,
    message: `Lazarus: modernize codebase\n\nAutomatically modernized by Lazarus resurrection engine.`,
    tree: tree.sha,
    parents: [baseSha],
  })

  await octokit.git.updateRef({
    owner,
    repo,
    ref: `heads/${branchName}`,
    sha: commit.sha,
  })

  const { data: pr } = await octokit.pulls.create({
    owner,
    repo,
    title: 'Lazarus: Modernize legacy codebase',
    body: [
      '## Lazarus Resurrection',
      '',
      'This PR was automatically generated by [Lazarus](https://lazarus.dev) — the legacy code resurrection engine.',
      '',
      '### What changed',
      '- Updated deprecated packages to modern equivalents',
      '- Converted to TypeScript where applicable',
      '- Modernized framework patterns (hooks, composition API, etc.)',
      '- Added security improvements (helmet, CORS, rate limiting)',
      '',
      '> All original functionality has been preserved.',
    ].join('\n'),
    head: branchName,
    base: defaultBranch,
  })

  return pr.html_url
}

export async function getUserRepos(
  octokit: Octokit
): Promise<
  Array<{
    fullName: string
    name: string
    owner: string
    private: boolean
    language: string | null
    updatedAt: string
  }>
> {
  const { data } = await octokit.repos.listForAuthenticatedUser({
    sort: 'updated',
    per_page: 50,
  })

  return data.map((repo) => ({
    fullName: repo.full_name,
    name: repo.name,
    owner: repo.owner.login,
    private: repo.private,
    language: repo.language,
    updatedAt: repo.updated_at ?? '',
  }))
}
